name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install Android SDK 34
        run: |
          yes | sdkmanager --install "platforms;android-34" "build-tools;34.0.0"

      - name: Fix compileSdk
        run: |
          sed -i 's/compileSdk = 35/compileSdk = 34/g' android/app/build.gradle
          sed -i 's/targetSdk = 35/targetSdk = 34/g' android/app/build.gradle

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: safetrace-apk
          path: build/app/outputs/flutter-apk/app-release.apk
